// Sound effects for the app
export const playSound = (type: 'click' | 'success' | 'error' | 'notification') => {
  const sounds = {
    click: new Audio('data:audio/wav;base64,UklGRpwAAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YXgAAAAoAIgA+ADKAIwAZABWAGQAiACyANQA6AD0APgA9ADoANQAsgCIAGQAVgBkAIgAyAD4AIgAKAAAAOj/yP+I/2T/Vv9k/4j/sv/U/+j/9P/4//T/6P/U/7L/iP9k/1b/ZP+I/8j/+P+I/ygAAA=='),
    success: new Audio('data:audio/wav;base64,UklGRrAAAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YYwAAAAMAGAAsADwACgBMAEoARAB4ACwAHAAMAAgACAAMABwALAA4AAQASgBMAEoAfAAYAAwAAAA4P+w/3D/MP8g/yD/MP9w/7D/4P8QACgAMAAoAPD/YAAwAAAA4P+w/3D/MP8g/yD/MP9w/7D/4P8QACgAMAAoAPD/YAAwAAAA'),
    error: new Audio('data:audio/wav;base64,UklGRpAAAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YWwAAAA4AHAApADIANwA5ADcAMgApABwADgAAAA4AHAApADIANwA5ADcAMgApABwADgAAAA4AHAApADIANwA5ADcAMgApABwADgAAAA='),
    notification: new Audio('data:audio/wav;base64,UklGRqQAAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YYAAAAAwAGAAmADAANgA4ADYAMAAmABgADAAAAAQAEAAcACYALAAwACwAJgAcABAABAAAAAQAEAAcACYALAAwACwAJgAcABAABAAAAAwAGAAmADAANgA4ADYAMAAmABgADAAAAAQAEAAcACYALAAwACwAJgAcABAABAAAAAQAEAAcACYALAAwACwAJgAcABAABAAAAAA')
  };

  const sound = sounds[type];
  sound.volume = 0.5;
  sound.play().catch(() => {
    // Ignore errors from browsers that block autoplay
  });
};